In [1]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Show all columns in dataframe
pd.set_option("display.max_columns", None)

sns.set_theme(style="whitegrid")

In [2]:
# Load dataset
df = pd.read_csv("/content/drive/MyDrive/house_sale.csv")

# First 5 rows
df.head()

,id_x,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,img_url,id_y,estate_id,estate_rel_url_y,datetime_scrape_y,description,unit_price,total_price,currency_y,owner_name,owner_title,shop_name,shop_title,address,lat,lng,updated,views,day_y,hour_y,estate_details_id_x,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_details_id_y,estate_rel_url,extra_info
0,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/alqi-satqi?page=174,/items/4521724,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,92e82ea2-e1f3-4c2d-a284-151efd99281e,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/items/4521724,2024-10-05 22:14:10.089116+00,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,AZN,Kamran,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,yeniləndi: dünən 23:52,1155,05.10.2024,23:52,92e82ea2-e1f3-4c2d-a284-151efd99281e,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,92e82ea2-e1f3-4c2d-a284-151efd99281e,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/alqi-satqi?page=250,/items/4669294,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,https://bina.azstatic.com/uploads/f460x345/202...,505eaf81-6bc8-4094-9b00-aa82066548ee,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/items/4669294,2024-10-05 22:14:10.089116+00,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,AZN,Dasinmaz Emlak,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,yeniləndi: 04 oktyabr 2024,218,04.10.2024,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,505eaf81-6bc8-4094-9b00-aa82066548ee,/items/4669294,Binəqədi r.* Biləcəri q.
2,55c36fb1-a3af-476e-ba17-a81f6795be8d,/alqi-satqi?page=250,/items/4669293,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,fa63b201-999d-43b5-a61a-778d9d79a6c6,55c36fb1-a3af-476e-ba17-a81f6795be8d,/items/4669293,2024-10-05 22:14:10.089116+00,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,AZN,Məhəmməd,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,yeniləndi: 04 oktyabr 2024,190,04.10.2024,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,fa63b201-999d-43b5-a61a-778d9d79a6c6,/items/4669293,İnşaatçılar m.* Yasamal r.
3,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/alqi-satqi?page=250,/items/4647811,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,https://bina.azstatic.com/uploads/f460x345/202...,5db56980-05cc-4925-b55b-f58fb3f4d2b6,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/items/4647811,2024-10-05 22:14:10.089116+00,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,AZN,Elçin,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,yeniləndi: 04 oktyabr 2024,1314,04.10.2024,NaN,5db56980-05cc-4925-b55b-f58fb3f4d2b6,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,5db56980-05cc-4925-b55b-f58fb3f4d2b6,/items/4647811,Suraxanı r.* Qaraçuxur q.
4,22d840df-9283-4112-bc71-7432511fc776,/alqi-satqi?page=250,/items/4638863,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,d71cf9a9-86dd-4162-b540-6252a8659a09,22d840df-9283-4112-bc71-7432511fc776,/items/4638863,2024-10-05 22:14:10.089116+00,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,AZN,Dürdanə,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,yeniləndi: 04 oktyabr 2024,240,04.10.2024,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,d71cf9a9-86dd-4162-b540-6252a8659a09,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

In [3]:
df.shape

(100775, 51)

In [4]:
df.columns

Index(['id_x', 'rel_url', 'estate_rel_url_x', 'datetime_scrape_x', 'price',
       'currency_x', 'location', 'attributes', 'city_when', 'city', 'day_x',
       'hour_x', 'repair', 'vip', 'featured', 'products_label', 'bill_of_sale',
       'mortgage', 'img_url', 'id_y', 'estate_id', 'estate_rel_url_y',
       'datetime_scrape_y', 'description', 'unit_price', 'total_price',
       'currency_y', 'owner_name', 'owner_title', 'shop_name', 'shop_title',
       'address', 'lat', 'lng', 'updated', 'views', 'day_y', 'hour_y',
       'estate_details_id_x', 'Binanın növü', 'Kateqoriya', 'Mərtəbə',
       'Otaq sayı', 'Sahə', 'Torpaq sahəsi', 'Təmir', 'Çıxarış', 'İpoteka',
       'estate_details_id_y', 'estate_rel_url', 'extra_info'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 51 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_x                 100775 non-null  object
 1   rel_url              100775 non-null  object
 2   estate_rel_url_x     100775 non-null  object
 3   datetime_scrape_x    100775 non-null  object
 4   price                100775 non-null  float64
 5   currency_x           100775 non-null  object
 6   location             100775 non-null  object
 7   attributes           100775 non-null  object
 8   city_when            100775 non-null  object
 9   city                 100775 non-null  object
 10  day_x                100775 non-null  object
 11  hour_x               100775 non-null  object
 12  repair               81612 non-null   object
 13  vip                  8596 non-null    object
 14  featured             3149 non-null    object
 15  products_label       72630 non-null   object
 16  bill_of_sale         79565 non-null   object
 17  mortgage             32939 non-null   object
 18  img_url              100775 non-null  object
 19  id_y                 100775 non-null  object
 20  estate_id            100775 non-null  object
 21  estate_rel_url_y     100775 non-null  object
 22  datetime_scrape_y    100775 non-null  object
 23  description          100510 non-null  object
 24  unit_price           75996 non-null   object
 25  total_price          100775 non-null  float64
 26  currency_y           100775 non-null  object
 27  owner_name           100118 non-null  object
 28  owner_title          100118 non-null  object
 29  shop_name            72018 non-null   object
 30  shop_title           72018 non-null   object
 31  address              100775 non-null  object
 32  lat                  100775 non-null  float64
 33  lng                  100775 non-null  float64
 34  updated              100775 non-null  object
 35  views                100775 non-null  int64
 36  day_y                100775 non-null  object
 37  hour_y               15631 non-null   object
 38  estate_details_id_x  100775 non-null  object
 39  Binanın növü         154 non-null     object
 40  Kateqoriya           100775 non-null  object
 41  Mərtəbə              75996 non-null   object
 42  Otaq sayı            91363 non-null   float64
 43  Sahə                 100775 non-null  object
 44  Torpaq sahəsi        15571 non-null   object
 45  Təmir                94774 non-null   object
 46  Çıxarış              100775 non-null  object
 47  İpoteka              32939 non-null   object
 48  estate_details_id_y  100775 non-null  object
 49  estate_rel_url       100775 non-null  object
 50  extra_info           100775 non-null  object
dtypes: float64(5), int64(1), object(45)
memory usage: 39.2+ MB

In [6]:
df.tail()

,id_x,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,img_url,id_y,estate_id,estate_rel_url_y,datetime_scrape_y,description,unit_price,total_price,currency_y,owner_name,owner_title,shop_name,shop_title,address,lat,lng,updated,views,day_y,hour_y,estate_details_id_x,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_details_id_y,estate_rel_url,extra_info
100770,b033ac14-d674-48a7-bc5c-3057bce7dd89,/alqi-satqi?page=296,/items/4774188,2024-11-19 20:46:55.308758,170000.0,AZN,Binəqədi q.,"6 otaqlı, 250 m²","Bakı, dünən 17:09",bakı,19.11.2024,17:09,Təmirli,NaN,NaN,NaN,NaN,NaN,https://bina.azstatic.com/uploads/f460x345/202...,46eb114c-6b59-414d-8c40-fc211190ff46,b033ac14-d674-48a7-bc5c-3057bce7dd89,/items/4774188,2024-11-19 20:49:57.700068,Ev mənimdir heç bir makler yoxdur.Şəxsi yaşayı...,NaN,170000.0,AZN,Orxan,mülkiyyətçi,NaN,NaN,Binəqədi şossesi donge 1,40.449401,49.774129,yeniləndi: 18 noyabr 2024,79,18.11.2024,NaN,46eb114c-6b59-414d-8c40-fc211190ff46,NaN,Həyət evi/Bağ evi,NaN,6.0,250 m²,3.5 sot,var,yoxdur,NaN,46eb114c-6b59-414d-8c40-fc211190ff46,/items/4774188,Binəqədi r.* Binəqədi q.
100771,b614e043-2712-4eb8-9a1e-723ed81ee489,/alqi-satqi?page=296,/items/3921717,2024-11-19 20:46:55.308758,520000.0,AZN,Mərdəkan q.,"4 otaqlı, 220 m²","Bakı, dünən 17:08",bakı,19.11.2024,17:08,Təmirli,NaN,NaN,Agentlik,Çıxarış var,İpoteka var,https://bina.azstatic.com/uploads/f460x345/202...,9bb02fc6-4f69-4f3e-95b3-2049e968e086,b614e043-2712-4eb8-9a1e-723ed81ee489,/items/3921717,2024-11-19 20:49:57.700068,Bakı Bağları şirkəti sizə ekoloji təmiz Mərdək...,NaN,520000.0,AZN,Ağa,vasitəçi (agent),Bakı Bağları,Daşınmaz əmlak agentliyi,Güney Azərbaycan küçəsi 7,40.491947,50.169690,yeniləndi: 18 noyabr 2024,971,18.11.2024,NaN,9bb02fc6-4f69-4f3e-95b3-2049e968e086,NaN,Həyət evi/Bağ evi,NaN,4.0,220 m²,11 sot,var,var,var,9bb02fc6-4f69-4f3e-95b3-2049e968e086,/items/3921717,Xəzər r.* Mərdəkan q.
100772,633d83f9-3a32-43fa-b089-b6c7085108a1,/alqi-satqi?page=296,/items/3933573,2024-11-19 20:46:55.308758,650000.0,AZN,Mərdəkan q.,"5 otaqlı, 350 m²","Bakı, dünən 17:08",bakı,19.11.2024,17:08,Təmirli,NaN,NaN,Agentlik,Çıxarış var,İpoteka var,https://bina.azstatic.com/uploads/f460x345/202...,29b3333e-e695-4cb6-bf75-f7f22225712d,633d83f9-3a32-43fa-b089-b6c7085108a1,/items/3933573,2024-11-19 20:49:57.700068,Bakı Bağları şirkəti Mərdəkan qəsəbəsində Dükk...,NaN,650000.0,AZN,Ağa,vasitəçi (agent),Bakı Bağları,Daşınmaz əmlak agentliyi,Əliheydər Qarayev küçəsi 10,40.486308,50.167252,yeniləndi: 18 noyabr 2024,1921,18.11.2024,NaN,29b3333e-e695-4cb6-bf75-f7f22225712d,NaN,Həyət evi/Bağ evi,NaN,5.0,350 m²,7 sot,var,var,var,29b3333e-e695-4cb6-bf75-f7f22225712d,/items/3933573,Xəzər r.* Mərdəkan q.
100773,ed8c1be0-b5a2-48a7-ba56-8d9e8389bb75,/alqi-satqi?page=296,/items/4774186,2024-11-19 20:46:55.308758,310000.0,AZN,20 Yanvar m.,"3 otaqlı, 130 m², 4/19 mərtəbə","Bakı, dünən 17:08",bakı,19.11.2024,17:08,Təmirli,NaN,NaN,Agentlik,Çıxarış var,İpoteka var,https://bina.azstatic.com/uploads/f460x345/202...,cfa88cfc-75a3-4657-8822-b11c82483164,ed8c1be0-b5a2-48a7-ba56-8d9e8389bb75,/items/4774186,2024-11-19 20:49:57.700068,"Yasamal rayonu, 20 yanvar metrosu yaxınlığında...",2 380 AZN/m²,310000.0,AZN,Ruqiyyə xanım,vasitəçi (agent),Home'L Estate Agency,Daşınmaz əmlak agentliyi,Moskva prospekti,40.412761,49.800789,yeniləndi: 18 noyabr 2024,61,18.11.2024,NaN,cfa88cfc-75a3-4657-8822-b11c82483164,NaN,Yeni tikili,4 / 19,3.0,130 m²,NaN,var,var,var,cfa88cfc-75a3-4657-8822-b11c82483164,/items/4774186,20 Yanvar m.* Yasamal r.
100774,e85db6c0-141d-44a3-a078-dcb4a4641091,/alqi-satqi?page=296,/items/4655312,2024-11-19 20:46:55.308758,165000.0,AZN,Nərimanov r.,"2 otaqlı, 55 m², 13/15 mərtəbə","Bakı, dünən 17:17",bakı,19.11.2024,17:17,Təmirli,NaN,NaN,Agentlik,NaN,NaN,https://bina.azstatic.com/uploads/f460x345/202...,1af4df10-8bfe-4d29-8964-9d8533cd3883,e85db6c0-141d-44a3-a078-dcb4a4641091,/items/4655312,2024-11-19 20:49:57.700068,* EAST Residence ** Ünvan : Qarabağ küç.\n* M...,3 000 AZN/m²,165000.0,AZN,Vüsalə,vasitəçi (agent),Real Əmlak Nərimanov,Daşınmaz əmlak agentliyi,Qarabağ küçəsi,40.389061,49.856563,yeniləndi: 18 noyabr 2024,161,18.11.2024,NaN,1af4df10-8bfe-4d29-8964-9d8533cd3883,NaN,Yeni tikili,13 / 15,2.0,55 m²,NaN,var,yoxdur,NaN,1af4df10-8bfe-4d29-8964-9d8533cd3883,/items/4655312,Şərq bazarı * Nərimanov r.

In [7]:
df.nunique().sort_values()

currency_x                  1
repair                      1
featured                    1
vip                         1
currency_y                  1
shop_title                  1
mortgage                    1
bill_of_sale                1
İpoteka                     1
products_label              2
Təmir                       2
owner_title                 2
Çıxarış                     2
Binanın növü                3
Kateqoriya                  7
city                        8
Otaq sayı                  19
day_x                      36
datetime_scrape_x          36
day_y                      38
location                  142
datetime_scrape_y         152
Torpaq sahəsi             188
shop_name                 316
Mərtəbə                   392
rel_url                   411
unit_price                814
hour_y                   1028
updated                  1145
hour_x                   1226
city_when                1504
Sahə                     1804
price                    2772
total_price              2772
extra_info               3000
owner_name               5448
views                    5896
address                 16716
attributes              21347
lng                     57207
lat                     57991
description             63385
estate_rel_url          64454
estate_rel_url_y        64454
estate_rel_url_x        64454
img_url                 64990
id_x                   100775
estate_id              100775
id_y                   100775
estate_details_id_x    100775
estate_details_id_y    100775
dtype: int64

# **Data Cleaning**

## Removing Identifier Columns

The columns `id_x`, `id_y`, `estate_id`, `estate_details_id_x`, and `estate_details_id_y` are unique identifiers assigned to each property record.

These columns are useful for database management and tracking individual records, but they do not contain meaningful information about property characteristics such as price, location, size, or other real estate features.

Since identifier columns do not contribute to exploratory data analysis and may introduce unnecessary complexity, they are removed from the dataset.

In [8]:
df.drop(columns=[
    "id_x",
    "id_y",
    "estate_id",
    "estate_details_id_x",
    "estate_details_id_y"
], inplace=True)

In [9]:
df.head()

,rel_url,estate_rel_url_x,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,img_url,estate_rel_url_y,datetime_scrape_y,description,unit_price,total_price,currency_y,owner_name,owner_title,shop_name,shop_title,address,lat,lng,updated,views,day_y,hour_y,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_rel_url,extra_info
0,/alqi-satqi?page=174,/items/4521724,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,/items/4521724,2024-10-05 22:14:10.089116+00,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,AZN,Kamran,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,yeniləndi: dünən 23:52,1155,05.10.2024,23:52,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,/alqi-satqi?page=250,/items/4669294,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,https://bina.azstatic.com/uploads/f460x345/202...,/items/4669294,2024-10-05 22:14:10.089116+00,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,AZN,Dasinmaz Emlak,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,yeniləndi: 04 oktyabr 2024,218,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,/items/4669294,Binəqədi r.* Biləcəri q.
2,/alqi-satqi?page=250,/items/4669293,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,/items/4669293,2024-10-05 22:14:10.089116+00,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,AZN,Məhəmməd,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,yeniləndi: 04 oktyabr 2024,190,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,/items/4669293,İnşaatçılar m.* Yasamal r.
3,/alqi-satqi?page=250,/items/4647811,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,https://bina.azstatic.com/uploads/f460x345/202...,/items/4647811,2024-10-05 22:14:10.089116+00,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,AZN,Elçin,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,yeniləndi: 04 oktyabr 2024,1314,04.10.2024,NaN,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,/items/4647811,Suraxanı r.* Qaraçuxur q.
4,/alqi-satqi?page=250,/items/4638863,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,https://bina.azstatic.com/uploads/f460x345/202...,/items/4638863,2024-10-05 22:14:10.089116+00,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,AZN,Dürdanə,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,yeniləndi: 04 oktyabr 2024,240,04.10.2024,NaN,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

## Removing URL and Image Reference Columns

The columns `img_url`, `rel_url`, `estate_rel_url`, `estate_rel_url_x`, and `estate_rel_url_y` contain website references and image links collected during the web scraping process.

These columns only provide access information to the original online listings and do not describe any property characteristics such as price, location, size, or other relevant attributes.

Since these features do not provide analytical value for exploratory data analysis, they are removed to reduce unnecessary complexity and keep the dataset focused on meaningful variables.

In [10]:
df.drop(columns=[
    "img_url",
    "rel_url",
    "estate_rel_url",
    "estate_rel_url_x",
    "estate_rel_url_y"
], inplace=True)

In [11]:
df.head()

,datetime_scrape_x,price,currency_x,location,attributes,city_when,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,datetime_scrape_y,description,unit_price,total_price,currency_y,owner_name,owner_title,shop_name,shop_title,address,lat,lng,updated,views,day_y,hour_y,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,extra_info
0,2024-10-05 22:07:37.60613+00,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,2024-10-05 22:14:10.089116+00,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,AZN,Kamran,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,yeniləndi: dünən 23:52,1155,05.10.2024,23:52,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,2024-10-05 22:07:37.60613+00,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,2024-10-05 22:14:10.089116+00,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,AZN,Dasinmaz Emlak,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,yeniləndi: 04 oktyabr 2024,218,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,Binəqədi r.* Biləcəri q.
2,2024-10-05 22:07:37.60613+00,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,2024-10-05 22:14:10.089116+00,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,AZN,Məhəmməd,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,yeniləndi: 04 oktyabr 2024,190,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,İnşaatçılar m.* Yasamal r.
3,2024-10-05 22:07:37.60613+00,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,2024-10-05 22:14:10.089116+00,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,AZN,Elçin,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,yeniləndi: 04 oktyabr 2024,1314,04.10.2024,NaN,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,Suraxanı r.* Qaraçuxur q.
4,2024-10-05 22:07:37.60613+00,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,2024-10-05 22:14:10.089116+00,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,AZN,Dürdanə,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,yeniləndi: 04 oktyabr 2024,240,04.10.2024,NaN,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

## Removing Scraping Timestamp Columns

The columns `datetime_scrape_x` and `datetime_scrape_y` represent the timestamps when the data was collected during the web scraping process.

These columns describe the data extraction process rather than the actual characteristics of the properties. Since scraping timestamps do not provide meaningful information about property prices, locations, or features, they are removed from the dataset to focus on relevant analytical variables.

In [12]:
df.drop(columns=[
    "datetime_scrape_x",
    "datetime_scrape_y"
], inplace=True)

In [13]:
df.head()

,price,currency_x,location,attributes,city_when,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,description,unit_price,total_price,currency_y,owner_name,owner_title,shop_name,shop_title,address,lat,lng,updated,views,day_y,hour_y,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,extra_info
0,499999.0,AZN,Səbail r.,"4 otaqlı, 145 m², 7/9 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3 450 AZN/m²,499999.0,AZN,Kamran,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,yeniləndi: dünən 23:52,1155,05.10.2024,23:52,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,77000.0,AZN,Biləcəri q.,"4 otaqlı, 90 m²","Bakı, dünən 23:56",bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",NaN,77000.0,AZN,Dasinmaz Emlak,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,yeniləndi: 04 oktyabr 2024,218,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,Binəqədi r.* Biləcəri q.
2,92000.0,AZN,İnşaatçılar m.,"3 otaqlı, 60 m²","Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,NaN,92000.0,AZN,Məhəmməd,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,yeniləndi: 04 oktyabr 2024,190,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,İnşaatçılar m.* Yasamal r.
3,95000.0,AZN,Qaraçuxur q.,130 m²,"Bakı, dünən 23:55",bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,Barter maraqlidir üstünlük maşina verilir\nHər...,NaN,95000.0,AZN,Elçin,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,yeniləndi: 04 oktyabr 2024,1314,04.10.2024,NaN,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,Suraxanı r.* Qaraçuxur q.
4,220000.0,AZN,Əhmədli m.,"3 otaqlı, 100 m², 15/16 mərtəbə","Bakı, dünən 23:52",bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2 200 AZN/m²,220000.0,AZN,Dürdanə,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,yeniləndi: 04 oktyabr 2024,240,04.10.2024,NaN,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

## Removing Constant Currency Columns

The columns `currency_x` and `currency_y` contain the currency information for property prices.

After checking the unique values, it was observed that all records use the same currency (`AZN`). Since these columns contain no variation and do not provide additional information for exploratory data analysis, they are removed from the dataset.

In [14]:
df["currency_x"].nunique(), df["currency_y"].nunique()

(1, 1)

In [15]:
df["currency_y"].value_counts(dropna=False)

currency_y
AZN    100775
Name: count, dtype: int64

In [16]:
df["currency_x"].value_counts(dropna=False)

currency_x
AZN    100775
Name: count, dtype: int64

In [17]:
df.drop(columns=[
    "currency_x",
    "currency_y"
], inplace=True)

## Removing Redundant Location-Time Column

The column `city_when` combines location and time-related information in a single text field.

However, the same information is already available in separate columns:

* `city` for location information.
* `day_x` for the advertisement date.
* `hour_x` for the advertisement time.

Since `city_when` contains redundant information and is less suitable for analysis compared to the separated columns, it is removed from the dataset.

In [18]:
df["city_when"].head(10)

0    Bakı, dünən 23:52
1    Bakı, dünən 23:56
2    Bakı, dünən 23:55
3    Bakı, dünən 23:55
4    Bakı, dünən 23:52
5    Bakı, dünən 23:52
6    Bakı, dünən 23:51
7    Bakı, dünən 23:49
8    Bakı, dünən 23:48
9    Bakı, dünən 23:48
Name: city_when, dtype: object

In [19]:
df[["city_when", "city", "day_x", "hour_x"]].head(10)

           city_when  city       day_x hour_x
0  Bakı, dünən 23:52  bakı  05.10.2024  23:52
1  Bakı, dünən 23:56  bakı  05.10.2024  23:56
2  Bakı, dünən 23:55  bakı  05.10.2024  23:55
3  Bakı, dünən 23:55  bakı  05.10.2024  23:55
4  Bakı, dünən 23:52  bakı  05.10.2024  23:52
5  Bakı, dünən 23:52  bakı  05.10.2024  23:52
6  Bakı, dünən 23:51  bakı  05.10.2024  23:51
7  Bakı, dünən 23:49  bakı  05.10.2024  23:49
8  Bakı, dünən 23:48  bakı  05.10.2024  23:48
9  Bakı, dünən 23:48  bakı  05.10.2024  23:48

In [20]:
df.drop(columns="city_when", inplace=True)

## Removing Redundant Attribute Column

The column `attributes` contains combined information about property characteristics in a single text format.

After comparing this column with existing features, it was observed that the same information is already available in separate columns:

* `Otaq sayı` for the number of rooms.
* `Sahə` for the property area.
* `Mərtəbə` for floor information.

Since `attributes` does not provide additional information and duplicates existing features in an unstructured format, it is removed to keep the dataset cleaner and easier to analyze.

In [21]:
df["attributes"].head(10)

0      4 otaqlı, 145 m², 7/9 mərtəbə
1                    4 otaqlı, 90 m²
2                    3 otaqlı, 60 m²
3                             130 m²
4    3 otaqlı, 100 m², 15/16 mərtəbə
5      4 otaqlı, 130 m², 3/4 mərtəbə
6       3 otaqlı, 70 m², 2/5 mərtəbə
7     3 otaqlı, 153 m², 3/18 mərtəbə
8                             485 m²
9    3 otaqlı, 104 m², 11/13 mərtəbə
Name: attributes, dtype: object

In [22]:
df["attributes"].nunique()

21347

In [23]:
df[[
    "attributes",
    "Otaq sayı",
    "Sahə",
    "Mərtəbə"
]].head(10)

                        attributes  Otaq sayı    Sahə  Mərtəbə
0    4 otaqlı, 145 m², 7/9 mərtəbə        4.0  145 m²    7 / 9
1                  4 otaqlı, 90 m²        4.0   90 m²      NaN
2                  3 otaqlı, 60 m²        3.0   60 m²      NaN
3                           130 m²        NaN  130 m²      NaN
4  3 otaqlı, 100 m², 15/16 mərtəbə        3.0  100 m²  15 / 16
5    4 otaqlı, 130 m², 3/4 mərtəbə        4.0  130 m²    3 / 4
6     3 otaqlı, 70 m², 2/5 mərtəbə        3.0   70 m²    2 / 5
7   3 otaqlı, 153 m², 3/18 mərtəbə        3.0  153 m²   3 / 18
8                           485 m²        NaN  485 m²      NaN
9  3 otaqlı, 104 m², 11/13 mərtəbə        3.0  104 m²  11 / 13

In [24]:
df.drop(columns="attributes", inplace=True)

## Removing Non-Analytical Columns

### Removing `description`

The `description` column contains free-text information written by property owners or agents. Although this data could be useful for Natural Language Processing (NLP) tasks, it is not suitable for this exploratory data analysis because it consists of unstructured text with a high number of unique values.

Since the analysis focuses on structured property features such as price, location, size, and property characteristics, the `description` column is removed to reduce complexity and improve dataset readability.

---

### Removing `owner_name`

The `owner_name` column contains personal names of property owners or listing providers. This information does not provide meaningful insights into property characteristics, pricing patterns, or market behavior.

Since it represents personal identification information rather than an analytical feature, the `owner_name` column is removed from the dataset.

---

### Removing `updated`

The `updated` column contains information about when a property listing was last updated on the website.

This information represents website activity and data collection details rather than property-related characteristics. Since it does not contribute to understanding property prices or features, the `updated` column is removed.

In [25]:
df.drop(columns=[
    "description",
    "owner_name",
    "updated"
], inplace=True)

In [26]:
df.head()

,price,location,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,unit_price,total_price,owner_title,shop_name,shop_title,address,lat,lng,views,day_y,hour_y,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,extra_info
0,499999.0,Səbail r.,bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,3 450 AZN/m²,499999.0,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,1155,05.10.2024,23:52,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,77000.0,Biləcəri q.,bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,NaN,77000.0,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,218,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,Binəqədi r.* Biləcəri q.
2,92000.0,İnşaatçılar m.,bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,NaN,92000.0,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,190,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,İnşaatçılar m.* Yasamal r.
3,95000.0,Qaraçuxur q.,bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,NaN,95000.0,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,1314,04.10.2024,NaN,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,Suraxanı r.* Qaraçuxur q.
4,220000.0,Əhmədli m.,bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,2 200 AZN/m²,220000.0,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,240,04.10.2024,NaN,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

## Removing `total_price` Column

The `total_price` column was compared with the `price` column to check whether they contained identical information.

The comparison showed that most values were the same, with only a small number of records having differences. Since `price` represents the primary property price used for analysis and `total_price` introduces potential inconsistency between two price sources, the `total_price` column is removed.

The `price` column is retained as the main property price feature.

In [27]:
(df["price"] == df["total_price"]).all()

np.False_

In [28]:
(df["price"] != df["total_price"]).sum()

np.int64(13)

In [29]:
df[df["price"] != df["total_price"]][
    ["price", "total_price"]
].head(10)

          price  total_price
5530   125000.0     121000.0
6423   160000.0     159000.0
18552  164000.0     162000.0
18715  290000.0     285000.0
19289  185000.0     184000.0
19396  124500.0     124000.0
19514   40000.0      41600.0
19542  396000.0     389000.0
19573  289000.0     285000.0
19811  121000.0     119000.0

In [30]:
df.drop(columns="total_price", inplace=True)

In [31]:
df.head()

,price,location,city,day_x,hour_x,repair,vip,featured,products_label,bill_of_sale,mortgage,unit_price,owner_title,shop_name,shop_title,address,lat,lng,views,day_y,hour_y,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,extra_info
0,499999.0,Səbail r.,bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,Çıxarış var,NaN,3 450 AZN/m²,mülkiyyətçi,NaN,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,1155,05.10.2024,23:52,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,77000.0,Biləcəri q.,bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,NaN,NaN,vasitəçi (agent),NaN,NaN,Biləcəri qəs.,40.420897,49.807035,218,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,Binəqədi r.* Biləcəri q.
2,92000.0,İnşaatçılar m.,bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,Çıxarış var,NaN,NaN,vasitəçi (agent),NaN,NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,190,04.10.2024,NaN,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,İnşaatçılar m.* Yasamal r.
3,95000.0,Qaraçuxur q.,bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,Çıxarış var,İpoteka var,NaN,mülkiyyətçi,NaN,NaN,Qaraçuxur qəs.,40.393614,49.981553,1314,04.10.2024,NaN,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,Suraxanı r.* Qaraçuxur q.
4,220000.0,Əhmədli m.,bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,Çıxarış var,NaN,2 200 AZN/m²,vasitəçi (agent),Elite Ofis,Daşınmaz əmlak agentliyi,Qaçaq Nəbi küç.,40.390550,49.957675,240,04.10.2024,NaN,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

In [32]:
df[[
    "day_x",
    "day_y",
    "hour_x",
    "hour_y"
]].head(20)

         day_x       day_y hour_x hour_y
0   05.10.2024  05.10.2024  23:52  23:52
1   05.10.2024  04.10.2024  23:56    NaN
2   05.10.2024  04.10.2024  23:55    NaN
3   05.10.2024  04.10.2024  23:55    NaN
4   05.10.2024  04.10.2024  23:52    NaN
5   05.10.2024  04.10.2024  23:52    NaN
6   05.10.2024  04.10.2024  23:51    NaN
7   05.10.2024  04.10.2024  23:49    NaN
8   05.10.2024  04.10.2024  23:48    NaN
9   05.10.2024  04.10.2024  23:48    NaN
10  05.10.2024  04.10.2024  23:44    NaN
11  05.10.2024  04.10.2024  23:41    NaN
12  05.10.2024  04.10.2024  23:40    NaN
13  05.10.2024  04.10.2024  23:38    NaN
14  05.10.2024  04.10.2024  23:37    NaN
15  05.10.2024  04.10.2024  23:36    NaN
16  05.10.2024  04.10.2024  23:35    NaN
17  05.10.2024  04.10.2024  23:32    NaN
18  05.10.2024  04.10.2024  23:27    NaN
19  05.10.2024  04.10.2024  23:27    NaN

In [33]:
df[[
    "day_x",
    "day_y",
    "hour_x",
    "hour_y"
]].nunique()

day_x       36
day_y       38
hour_x    1226
hour_y    1028
dtype: int64

## Removing Secondary Date and Time Columns

The columns `day_y` and `hour_y` represent additional date and time information collected from another source during the scraping process.

After comparing them with `day_x` and `hour_x`, it was observed that these columns contain many missing values and do not provide additional consistent information. The primary advertisement date and time are already available in `day_x` and `hour_x`, which are more complete and suitable for analysis.

Therefore, `day_y` and `hour_y` are removed to reduce redundancy and keep only the most relevant time-related features.

In [34]:
df.drop(columns=[
    "day_y",
    "hour_y"
], inplace=True)

## Removing Redundant Ownership Document Column

The columns `bill_of_sale` and `Çıxarış` represent the same property ownership document information.

After comparing both columns, it was observed that they contain identical information but in different formats. The `bill_of_sale` column uses a text-based format (`Çıxarış var` and missing values), while the `Çıxarış` column provides a cleaner categorical representation (`var` and `yoxdur`).

Since `Çıxarış` is more structured and suitable for analysis, the `bill_of_sale` column is removed to avoid redundancy.

In [35]:
df["bill_of_sale"].value_counts(dropna=False)

bill_of_sale
Çıxarış var    79565
NaN            21210
Name: count, dtype: int64

In [36]:
df["Çıxarış"].value_counts(dropna=False)

Çıxarış
var       79565
yoxdur    21210
Name: count, dtype: int64

In [37]:
df[[
    "bill_of_sale",
    "Çıxarış"
]].head(20)

   bill_of_sale Çıxarış
0   Çıxarış var     var
1           NaN  yoxdur
2   Çıxarış var     var
3   Çıxarış var     var
4   Çıxarış var     var
5   Çıxarış var     var
6   Çıxarış var     var
7   Çıxarış var     var
8   Çıxarış var     var
9           NaN  yoxdur
10          NaN  yoxdur
11  Çıxarış var     var
12  Çıxarış var     var
13  Çıxarış var     var
14  Çıxarış var     var
15  Çıxarış var     var
16  Çıxarış var     var
17          NaN  yoxdur
18  Çıxarış var     var
19  Çıxarış var     var

In [38]:
df.drop(columns="bill_of_sale", inplace=True)

## Removing Redundant Mortgage Column

The columns `mortgage` and `İpoteka` contain the same information about mortgage availability.

After comparing both columns, it was confirmed that they represent identical data. However, the `İpoteka` column has a clearer and more meaningful name for this dataset and is more suitable for analysis.

Therefore, the `mortgage` column is removed to avoid duplicate information and keep only the more interpretable feature.

In [39]:
df["mortgage"].value_counts(dropna=False)

mortgage
NaN            67836
İpoteka var    32939
Name: count, dtype: int64

In [40]:
df["İpoteka"].value_counts(dropna=False)

İpoteka
NaN    67836
var    32939
Name: count, dtype: int64

In [41]:
df[[
    "mortgage",
    "İpoteka"
]].head(20)

       mortgage İpoteka
0           NaN     NaN
1           NaN     NaN
2           NaN     NaN
3   İpoteka var     var
4           NaN     NaN
5           NaN     NaN
6           NaN     NaN
7           NaN     NaN
8           NaN     NaN
9           NaN     NaN
10          NaN     NaN
11  İpoteka var     var
12          NaN     NaN
13          NaN     NaN
14  İpoteka var     var
15  İpoteka var     var
16          NaN     NaN
17          NaN     NaN
18          NaN     NaN
19  İpoteka var     var

In [42]:
df.drop(columns="mortgage", inplace=True)

## Removing Low-Information Categorical Column

The `shop_title` column contains information about the listing source type. After analyzing its unique values, it was observed that this column contains only one meaningful category (`Daşınmaz əmlak agentliyi`) and missing values.

Since the column has very low variability and does not provide detailed information about the real estate provider, while more informative columns such as `owner_title` and `shop_name` are already available, `shop_title` is removed from the dataset.

In [43]:
df["shop_title"].value_counts(dropna=False)

shop_title
Daşınmaz əmlak agentliyi    72018
NaN                         28757
Name: count, dtype: int64

In [44]:
df["shop_title"].nunique()

1

In [45]:
df["shop_title"].isnull().mean()*100

np.float64(28.535847184321504)

In [46]:
df[["shop_title", "owner_title", "shop_name"]].head(20)

                  shop_title       owner_title         shop_name
0                        NaN       mülkiyyətçi               NaN
1                        NaN  vasitəçi (agent)               NaN
2                        NaN  vasitəçi (agent)               NaN
3                        NaN       mülkiyyətçi               NaN
4   Daşınmaz əmlak agentliyi  vasitəçi (agent)        Elite Ofis
5                        NaN  vasitəçi (agent)               NaN
6                        NaN  vasitəçi (agent)               NaN
7                        NaN  vasitəçi (agent)               NaN
8                        NaN       mülkiyyətçi               NaN
9   Daşınmaz əmlak agentliyi  vasitəçi (agent)          MS Group
10                       NaN       mülkiyyətçi               NaN
11                       NaN       mülkiyyətçi               NaN
12  Daşınmaz əmlak agentliyi  vasitəçi (agent)  New House Nəsimi
13                       NaN       mülkiyyətçi               NaN
14  Daşınmaz əmlak agentliyi  vasitəçi (agent)  VİP House Elmlər
15  Daşınmaz əmlak agentliyi  vasitəçi (agent)  VİP House Elmlər
16                       NaN  vasitəçi (agent)               NaN
17                       NaN  vasitəçi (agent)               NaN
18                       NaN       mülkiyyətçi               NaN
19                       NaN  vasitəçi (agent)               NaN

In [47]:
df.drop(columns="shop_title", inplace=True)

In [48]:
df.head()

,price,location,city,day_x,hour_x,repair,vip,featured,products_label,unit_price,owner_title,shop_name,address,lat,lng,views,Binanın növü,Kateqoriya,Mərtəbə,Otaq sayı,Sahə,Torpaq sahəsi,Təmir,Çıxarış,İpoteka,extra_info
0,499999.0,Səbail r.,bakı,05.10.2024,23:52,Təmirli,vipped,featured,NaN,3 450 AZN/m²,mülkiyyətçi,NaN,İzzət Nəbiyev küç.,40.358817,49.824092,1155,NaN,Köhnə tikili,7 / 9,4.0,145 m²,NaN,var,var,NaN,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.
1,77000.0,Biləcəri q.,bakı,05.10.2024,23:56,Təmirli,NaN,NaN,NaN,NaN,vasitəçi (agent),NaN,Biləcəri qəs.,40.420897,49.807035,218,NaN,Həyət evi/Bağ evi,NaN,4.0,90 m²,1.3 sot,var,yoxdur,NaN,Binəqədi r.* Biləcəri q.
2,92000.0,İnşaatçılar m.,bakı,05.10.2024,23:55,Təmirli,NaN,NaN,NaN,NaN,vasitəçi (agent),NaN,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,190,NaN,Həyət evi/Bağ evi,NaN,3.0,60 m²,0.1 sot,var,var,NaN,İnşaatçılar m.* Yasamal r.
3,95000.0,Qaraçuxur q.,bakı,05.10.2024,23:55,Təmirli,vipped,featured,NaN,NaN,mülkiyyətçi,NaN,Qaraçuxur qəs.,40.393614,49.981553,1314,NaN,Obyekt,NaN,NaN,130 m²,NaN,var,var,var,Suraxanı r.* Qaraçuxur q.
4,220000.0,Əhmədli m.,bakı,05.10.2024,23:52,Təmirli,NaN,NaN,Agentlik,2 200 AZN/m²,vasitəçi (agent),Elite Ofis,Qaçaq Nəbi küç.,40.390550,49.957675,240,NaN,Yeni tikili,15 / 16,3.0,100 m²,NaN,var,var,NaN,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...

## Removing Redundant Repair Column

The `repair` and `Təmir` columns both describe the renovation status of a property.

After comparing their values, it was observed that the `repair` column only indicates renovated properties (`Təmirli`) and stores non-renovated properties as missing values. In contrast, the `Təmir` column provides a more complete categorical representation by distinguishing between renovated (`var`) and non-renovated (`yoxdur`) properties.

Since `Təmir` contains more complete and informative data, the `repair` column is removed from the dataset.

In [49]:
df[["repair", "Təmir"]].head(20)

     repair   Təmir
0   Təmirli     var
1   Təmirli     var
2   Təmirli     var
3   Təmirli     var
4   Təmirli     var
5   Təmirli     var
6   Təmirli     var
7       NaN  yoxdur
8   Təmirli     var
9   Təmirli     var
10      NaN     NaN
11  Təmirli     var
12  Təmirli     var
13      NaN  yoxdur
14  Təmirli     var
15  Təmirli     var
16  Təmirli     var
17  Təmirli     var
18      NaN  yoxdur
19  Təmirli     var

In [50]:
df["repair"].value_counts(dropna=False)

repair
Təmirli    81612
NaN        19163
Name: count, dtype: int64

In [51]:
df["Təmir"].value_counts(dropna=False)

Təmir
var       81612
yoxdur    13162
NaN        6001
Name: count, dtype: int64

In [52]:
df.drop(columns="repair", inplace=True)

## Removing Unstructured Location Information

The `extra_info` column contains unstructured text describing nearby districts, metro stations, and landmarks.

Although this information may provide additional context, it is highly inconsistent, contains thousands of unique text combinations, and overlaps with structured location features such as `location`, `address`, `lat`, and `lng`.

Since the same geographical information is already represented in a cleaner and more structured format, the `extra_info` column is removed to simplify the dataset and avoid redundant textual information.

In [61]:
df["extra_info"].nunique()

3000

In [62]:
df["extra_info"].isnull().mean() * 100

np.float64(0.0)

In [63]:
df["extra_info"].sample(20, random_state=42)

980                                              Səbail r.
87688                 Sea Breeze * Sabunçu r.* Nardaran q.
46608    ASAN Xidmət №2 * Ağ şəhər * Şah İsmayıl Xətai ...
92171                                          Suraxanı r.
45698                                Xəzər r.* Mərdəkan q.
32455                               Abşeron r.* Masazır q.
48501                             Sabunçu r.* Bakıxanov q.
45336                                           Abşeron r.
26970                                 Abşeron r.* Saray q.
35962    Ukrayna dairəsi * Həzi Aslanov m.* Əhmədli m.*...
31888                          Yasamal r.* Yeni Yasamal q.
64035    Hüseyn Cavid parkı * Elmlər Akademiyası m.* Te...
41691                       Şah İsmayıl Xətai m.* Xətai r.
36061                                            Səbail r.
6175                      Ağ şəhər * Xətai r.* Ağ şəhər q.
59674                               Sabunçu r.* Sabunçu q.
99130    Nəsimi bazarı * Park Zorge * Koala parkı * Nəs...
63776                            Suraxanı r.* Qaraçuxur q.
92409                             Suraxanı r.* Suraxanı q.
33225                                    Xəzər r.* Binə q.
Name: extra_info, dtype: object

In [64]:
df.drop(columns="extra_info", inplace=True)

## Removing Highly Incomplete Column

The `Binanın növü` column contains an extremely high percentage of missing values, making it unreliable for meaningful analysis.

Since only a very small number of records contain valid information, imputing the missing values would introduce significant bias and reduce data quality. Therefore, this column is removed from the dataset.

In [67]:
# Check missing values percentage for Binanın növü

df["Binanın növü"].isnull().mean() * 100

np.float64(99.84718432150831)

In [68]:
# Remove column with extremely high missing values

df.drop(columns="Binanın növü", inplace=True)

# **Getting to Know the Dataset**

## Dataset Shape

The dataset shape was examined to understand the size of the data.

The dataset contains rows representing real estate listings and columns representing property characteristics, location information, advertisement details, and numerical features.

In [70]:
df.shape

(100775, 23)

## Data Types Analysis

The data types of all columns were inspected to identify numerical, categorical, and text-based features.

Understanding data types is important before performing data cleaning, missing value handling, and feature engineering operations.

In [75]:
df.dtypes

price             float64
location           object
city               object
day_x              object
hour_x             object
vip                object
featured           object
products_label     object
unit_price         object
owner_title        object
shop_name          object
address            object
lat               float64
lng               float64
views               int64
Kateqoriya         object
Mərtəbə            object
Otaq sayı         float64
Sahə               object
Torpaq sahəsi      object
Təmir              object
Çıxarış            object
İpoteka            object
dtype: object

## Dataset Information

The `info()` method was used to examine column names, data types, and the number of non-null values.

This step helps identify columns with missing data and potential type conversion requirements.

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 23 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   price           100775 non-null  float64
 1   location        100775 non-null  object
 2   city            100775 non-null  object
 3   day_x           100775 non-null  object
 4   hour_x          100775 non-null  object
 5   vip             8596 non-null    object
 6   featured        3149 non-null    object
 7   products_label  72630 non-null   object
 8   unit_price      75996 non-null   object
 9   owner_title     100118 non-null  object
 10  shop_name       72018 non-null   object
 11  address         100775 non-null  object
 12  lat             100775 non-null  float64
 13  lng             100775 non-null  float64
 14  views           100775 non-null  int64
 15  Kateqoriya      100775 non-null  object
 16  Mərtəbə         75996 non-null   object
 17  Otaq sayı       91363 non-null   float64
 18  Sahə            100775 non-null  object
 19  Torpaq sahəsi   15571 non-null   object
 20  Təmir           94774 non-null   object
 21  Çıxarış         100775 non-null  object
 22  İpoteka         32939 non-null   object
dtypes: float64(4), int64(1), object(18)
memory usage: 17.7+ MB

## Statistical Summary

Descriptive statistics were calculated for numerical columns to understand the distribution of values.

The summary includes information such as mean, standard deviation, minimum, maximum, and quartile values.

In [73]:
df.describe()

              price            lat            lng          views     Otaq sayı
count  1.007750e+05  100775.000000  100775.000000  100775.000000  91363.000000
mean   3.423557e+05      40.410846      49.886371     700.065185      3.133468
std    2.042627e+06       0.083193       0.265008    1680.672574      1.372981
min    1.100000e+01      32.689217      12.591688      23.000000      1.000000
25%    1.450000e+05      40.381900      49.816470      99.000000      2.000000
50%    2.180000e+05      40.397219      49.852867     254.000000      3.000000
75%    3.380000e+05      40.420578      49.948995     680.000000      4.000000
max    6.000000e+08      41.774687      50.341059  113458.000000     20.000000

## Missing Values Analysis

Missing values were analyzed for each column by calculating both the number and percentage of missing observations.

This analysis helps determine the appropriate strategy for handling missing values, such as removing columns with excessive missingness or filling values where meaningful.

In [74]:
missing_values = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_values.sort_values(
    by="Missing Percentage",
    ascending=False
)

                Missing Count  Missing Percentage
featured                97626           96.875217
vip                     92179           91.470107
Torpaq sahəsi           85204           84.548747
İpoteka                 67836           67.314314
shop_name               28757           28.535847
products_label          28145           27.928554
unit_price              24779           24.588440
Mərtəbə                 24779           24.588440
Otaq sayı                9412            9.339618
Təmir                    6001            5.954850
owner_title               657            0.651947
price                       0            0.000000
hour_x                      0            0.000000
location                    0            0.000000
city                        0            0.000000
day_x                       0            0.000000
lng                         0            0.000000
lat                         0            0.000000
address                     0            0.000000
views                       0            0.000000
Kateqoriya                  0            0.000000
Sahə                        0            0.000000
Çıxarış                     0            0.000000

## Duplicate Data Check

Duplicate rows were checked to ensure that the dataset does not contain repeated observations.

Removing duplicate records prevents biased analysis and improves data quality.

In [76]:
df.duplicated().sum()

np.int64(0)

The analysis showed that there are no duplicate records in the dataset. Therefore, no duplicate removal operation was required.